global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server01'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server02'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server03'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server04'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server05'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server06'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server07'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']
  
  - job_name: 'server08'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server09'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server10'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9100']

  - job_name: 'server11'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182']

  - job_name: 'server12'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182']

  - job_name: 'server13'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182']

  - job_name: 'server14'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182'] 

  - job_name: 'server15'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182']

  - job_name: 'server16'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.0:9182']


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - https://www.website1.test
        - https://www.website2.test
        - https://www.website3.test
        - https://www.website4.test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        

